
#include <QtCore>

// This header is generated by Flex.
//#include "lexer.h"

// This header is generated by bison.
//#include "parser.h"

#include "base.h"

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);

    yyin = fopen("00.txt" , "r");

    yylex();

    fclose(yyin);

    return app.exec();
}



