
#include <QtCore>
#include <stdio.h>
#include <qfile.h>
#include <QByteArray>


// This header is generated by Flex.
//#include "lexer.h"

// This header is generated by bison.
//#include "parser.h"

#include "base.h"
#include "parser.h"

extern FILE *yyin;

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);

    QFile file("00.txt");

    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return 0;

    while (!file.atEnd()) {
        QByteArray line = file.readLine();

        YY_BUFFER_STATE bufferState = yy_scan_string(line.data());

        yyparse();

        yy_delete_buffer(bufferState);
    }


    return app.exec();
}



